name: alpha_generations
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  firebase_auth: ^5.5.1
  awesome_dialog: ^3.2.1
  google_sign_in: ^6.2.2
  animate_do: ^4.2.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  file_picker: ^9.2.1
  video_player: ^2.9.3
  chewie: ^1.10.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  shared_preferences: ^2.5.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  image_path: "images/logo.jpg"
  min_sdk_android: 21 #

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
